### PR TITLE
Add info command

### PR DESCRIPTION
**Pull request by nvthongswansea**
Add a gscloud info that quickly gives you a rough overview of the current working account.

- token.
- user ID.
- API URL used.
- Object counts of servers, storages, IP addresses, and PaaS services.

### CODE REVIEW

**Review by bkircher — CHANGES_REQUESTED** [review]
Thanks! Looks good so far. Can you make a couple of changes?

- Do not call os.Exit (or a function that calls os.Exit indirectly)
- Instead use RunE and return an error from function (checkout cmd.NewError)
- Use render.AsTable to print the output
- and allow `--json` flag and render.AsJSON

**Comment by bkircher** [comment]
Changed a couple of strings in 663c925a9562dbcf2489176d6a785974fb5b70f6

**Comment by bkircher** [comment]
Fixes https://github.com/gridscale/gscloud/issues/116

**Comment by nvthongswansea** [comment]
@bkircher Done.
JSON 
image

Table
image

**Comment by bkircher** [comment]
O.K. Finally came around to re-write this a bit.

Changes:
     - Fetch object counts concurrently (Much faster now. Actually bearable)
    - With --json flag: only print valid JSON to stdout


Looks mergable to me now. @nvthongswansea  can you take anther look here?

**Review by bkircher — APPROVED** [review]

**Comment by nvthongswansea** [comment]
LGTM.

**Comment by bkircher** [comment]
Thx @nvthongswansea !

**Pull request merged**
