### PR TITLE
fix iso-image ls --quiet to show only image-ids

### LINKED ISSUE #134: gscloud iso-image ls --quiet shows two tables
gscloud iso-image ls --quiet shows a list and then the complete table.

### PR DESCRIPTION
**Pull request by ghostwheel42**
closes #134

### CODE REVIEW

**Comment by nvthongswansea** [comment]
In stead of if-else, you could do if-return. That would give a bit of performance, since it returns right away when the condition is met (instead of checking other conditions and then return at the end of the function).

**Comment by ghostwheel42** [comment]
Yes, I know. I’ve decided to stick to the if-else style already present in the existing code, even though this is not the normally used go style.
I didn’t want to change too much of the existing code.

**Comment by nvthongswansea** [comment]
LGTM @bkircher any thoughts?

**Comment by bkircher** [comment]
Ja, looks good.

**Comment by bkircher** [comment]
Thanks @ghostwheel42 , @nvthongswansea!

**Pull request merged**
