### PR TITLE
Refactor gscloud to make it testable

### PR DESCRIPTION
**Pull request by nvthongswansea**
Changes:
- Remove dummy variables + unused files.
- Make some global variables local (since they don't need to be global).
- Remove multiple `init()` functions in `cmd` packages (https://github.com/gridscale/gscloud/commit/544ef9c350a89b10d6ecde75b85dc94e34156a11).
- Remove `cobra.OnInitialize` (https://github.com/gridscale/gscloud/commit/d7f6a6b2b086ab1c60221568b3c349508d2c7f86)
- Fix some small bugs (e.g: display a list of storages in JSON format, etc.)
- Use interfaces to make gscloud testable and more flexible to change.
- Add some sample unit tests.

@bkircher @c0dehard please test all commands again.

### CODE REVIEW

**Comment by c0dehard** [comment]
LGTM. Good job i like it very much, everything works for me 👍

**Comment by bkircher** [comment]
Would work for me in general. I like the two added tests for version and storage. Only issue I have is that it is a uncommon structure for cobra projects. So things like

`$ cobra add new-command --parent rootCmd`

won't work anymore. Also I would like to see this in the sub-command file:

```
func init() {
	rootCmd.AddCommand(newCommandCmd)
        # …
}
```
rather than touching this every time in `cmd/root.go`:
```
func init() {
        # …
	initMakeConfCmd()
	initK8SCmd()
	initStorageCmd()
	initVersionCmd()
        newCommand()
      # …
```

YMMV.

An alternative approach would be not refactoring this to named functions, using `Command.execute()` when testing, possibly replacing `Command.errWriter` or `Command.outWriter`, respectively. (Along with using `Command.Print` and friends. What do you think?

**Comment by nvthongswansea** [comment]
> Command



> Would work for me in general. I like the two added tests for version and storage. Only issue I have is that it is a uncommon structure for cobra projects. So things like
> 
> `$ cobra add new-command --parent rootCmd`
> 
> won't work anymore. Also I would like to see this in the sub-command file:
> 
> ```
> func init() {
> 	rootCmd.AddCommand(newCommandCmd)
>         # …
> }
> ```
> 
> rather than touching this every time in `cmd/root.go`:
> 
> ```
> func init() {
>         # …
> 	initMakeConfCmd()
> 	initK8SCmd()
> 	initStorageCmd()
> 	initVersionCmd()
>         newCommand()
>       # …
> ```
> 
> YMMV.
> 
> An alternative approach would be not refactoring this to named functions, using `Command.execute()` when testing, possibly replacing `Command.errWriter` or `Command.outWriter`, respectively. (Along with using `Command.Print` and friends). What do you think?

Good spot. I've never known `$ cobra add new-command --parent rootCmd` before, I thought the whole project was built from scratch.

**Comment by nvthongswansea** [comment]
@bkircher I have checked other cobra projects. Some of them don't follow the cobra's project structure (e.g: https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/cmd). What do you think?

**Comment by bkircher** [comment]
Okidoki, then lets go with this :+1:

**Pull request merged**
